/**
 * Derives the web image set from the photos extracted out of the agency's
 * AgestaNET listing PDFs (see _source-photos/). Run with `npm run images`.
 *
 * For every source photo we emit three WebP renditions plus a dominant colour
 * used as the blur-up placeholder tint, and write an index the app imports.
 */
import sharp from 'sharp'
import { readdir, mkdir, writeFile, stat } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const SRC = path.resolve(HERE, '../../_source-photos')
const OUT = path.resolve(HERE, '../public/properties')
const MAX_PER_PROPERTY = 30

const RENDITIONS = [
  { key: 'thumb', width: 420, quality: 66 },
  { key: 'card', width: 900, quality: 72 },
  { key: 'full', width: 1700, quality: 74 },
]

const hex = (c) => '#' + [c.r, c.g, c.b].map((v) => v.toString(16).padStart(2, '0')).join('')

async function run() {
  if (!existsSync(SRC)) throw new Error(`missing source photos at ${SRC}`)
  await mkdir(OUT, { recursive: true })

  const slugs = (await readdir(SRC, { withFileTypes: true }))
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort()

  const index = {}
  let emitted = 0
  let bytes = 0

  for (const slug of slugs) {
    const files = (await readdir(path.join(SRC, slug)))
      .filter((f) => /\.(jpe?g|png|webp)$/i.test(f))
      .sort()
      .slice(0, MAX_PER_PROPERTY)

    index[slug] = []

    for (const [i, file] of files.entries()) {
      const n = String(i + 1).padStart(2, '0')
      const input = path.join(SRC, slug, file)
      const img = sharp(input, { failOn: 'none' }).rotate()
      const meta = await img.metadata()
      const { dominant } = await sharp(input, { failOn: 'none' }).stats()

      const entry = {
        id: `${slug}-${n}`,
        w: meta.width ?? 0,
        h: meta.height ?? 0,
        color: hex(dominant),
      }

      for (const r of RENDITIONS) {
        const name = `${slug}-${n}-${r.key}.webp`
        const dest = path.join(OUT, name)
        await sharp(input, { failOn: 'none' })
          .rotate()
          .resize({ width: r.width, withoutEnlargement: true })
          .webp({ quality: r.quality, effort: 5 })
          .toFile(dest)
        entry[r.key] = name
        bytes += (await stat(dest)).size
        emitted++
      }
      index[slug].push(entry)
    }
    console.log(`  ${slug.padEnd(24)} ${String(files.length).padStart(3)} photos`)
  }

  const header = `// GENERATED by scripts/process-images.mjs — do not edit by hand.\n`
  await writeFile(
    path.resolve(HERE, '../src/data/photo-index.json'),
    JSON.stringify(index, null, 1),
  )
  await writeFile(path.resolve(HERE, '../src/data/photo-index.d.ts'), header)

  console.log(
    `\n${emitted} files, ${(bytes / 1024 / 1024).toFixed(1)} MB across ${slugs.length} properties`,
  )
}

run().catch((e) => {
  console.error(e)
  process.exit(1)
})
